package br.com.syngenta.message;

public enum MessageEnum {

	//PDF UTILS
	PDF_UTILS_ERROR_001, PDF_UTILS_ERROR_002, PDF_UTILS_ERROR_003,
	
	
	//XML UTILS
	XML_UTILS_ERROR_001, XML_UTILS_ERROR_002,
	
	
	//SERVICE
	XLM_PARSER_SERVICE_ERROR_001, XLM_PARSER_SERVICE_ERROR_002,
	
	//FILE UTILS
	FILE_UTILS_ERROR_001
	
}
